### ISSUE TITLE
Create a Directory Score explanation page

### ISSUE THREAD

**Issue by jonsamp** [react-native-directory/website#249]
# Feature Request

The directory displays a Directory Score. This score is not explained anywhere on the site itself. This issue is to create a page that explains how we calculate the score, then links to the code for those who are curious.

The score calculating script is written here: https://github.com/react-native-community/directory/blob/master/scripts/calculate-score.js

## Possible implementation

- Make all "Directory score" elements a link to another page (use next routes/pages to create a new page/url)
- The Directory score page should have a written out explanation of what the score is and how it is calculated.
- This would be a great spot to also instruct on how to make a great package, according to this directory's standards.

**Comment by Simek** [comment]
@jonsamp Good work! I'm going to close this issue because Directory Score explanation PR has been merged and the page is live.
