### ISSUE TITLE
Add GitHub action to validate json

### ISSUE THREAD

**Issue by brentvatne** [react-native-directory/website#283]
Should just run `yarn data:validate`

**Comment by Simek** [comment]
@brentvatne It looks like this script is currently a part of GH Workflows on PRs and deploy (has been added within https://github.com/react-native-directory/website/commit/6522a8fa00f9f9aa19d46f410329152de9078161):
* https://github.com/react-native-directory/website/blob/master/.github/workflows/test-and-validate.yml#L20

**Comment by brentvatne** [comment]
``
