### ISSUE TITLE
Library compatibility OpenCV

### ISSUE THREAD

**Issue by magiclown1** [react-native-directory/website#328]
Hi guys! 

I'm new to react-native/Expo, I would like to use OpenCV into my mobile app project.
I saw there's a way to do it by creating native modules ( this mean I can't use Expo and I need to use Objective-C/C++ for IOS and Java for Android)

Since I only want to play around with images matrix (data), I was wondering if I can directly work with JavaScript and use OpenCV.js or OpenCV4nodejs. I have not been able to import these library properly.  Is it even possible? If yes, can I do it with Expo?

Thanks a lot !!!
Have a nice day

**Comment by brentvatne** [comment]
hi there!

sorry i didn't notice this. you could potentially do this with a webview but i'm not totally sure. you can definitely do it if you run the opencv code on a server :)
